language: ruby
rvm:
  - 2.5.5
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec

before_install:
  - mysql -e "CREATE DATABASE ${DATABASE_NAME}_test;"

services:
  - mysql
  - redis-server
